services:
  traefik:
    image: ${REGISTRY_DHI:-dhi.io}/traefik:3.6
    ports:
      - ${PORT:-80}:${PORT:-80}
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--providers.file.watch=true"
      - --entrypoints.web.address=:${PORT:-80}
    volumes:
      - ./dynamic.yml:/etc/traefik/dynamic.yml

  itb-frontend:
    image: ${REGISTRY_BANIAN:-banianch}/itb:${WEBAPP_TAG:-latest}
    environment:
      - API_URL=${API_URL:-http://api.itb.localhost}
      - API_PORT=${PORT:-}
      - WEBAPP_URL=${WEBAPP_URL:-http://itb.localhost}
      - WEBAPP_PORT=${PORT:-}
    volumes:
      - ./output/frontend:/app/data
      - pb_data:/app/pb/pb_data

  itb-api:
    image: ${REGISTRY_BANIAN:-banianch}/itb-api:${API_TAG:-latest}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips=* --reload --reload-dir /app --log-level debug
    volumes:
      - ./output:/app/output
      - ./api/template_engine:/app/packages/template_engine
    environment:
      - WEBAPP_URL=${WEBAPP_URL:-http://itb.localhost}
      - WEBAPP_PORT=${PORT:-}
      - API_JSON_OUTPUT_PATH=${API_JSON_OUTPUT_PATH:-output/json}
      - API_JSON_FILENAME=${API_JSON_FILENAME:-data_modeler_structure.json}
      - API_TEMPLATE_OUTPUT_PATH=${API_TEMPLATE_OUTPUT_PATH:-output/templates}

  itb-docs:
    image: ${REGISTRY_DHI:-dhi.io}/busybox:1.37.0
    command: httpd -f -p 80 -h /www
    volumes:
      - ./docs:/www:ro

volumes: 
  pb_data:

networks:
  default:
    name: itb